[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
time_shared_nft = "DE1wx1MeAQeZQCepnd2Ukd5o2S7v6JJaRfuX1G3EG1rs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
